[project]
name = "coral-codediffreview-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "camel-ai[model-platforms]",
    "pillow>=11.2.1",
    "requests-oauthlib>=2.0.0",
    "sqlalchemy>=2.0.41",
]
